Repository metafy-social/python-scripts, pull requests merged in 2022-10, with the labels that each got.

#28 new code for ip checking
  scripts/Public_IP_Address/README.md
  scripts/Public_IP_Address/my_public_ip.py
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#33 Added Image Scraper
  scripts/Image Scraper/README.md
  scripts/Image Scraper/script.py
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#16 ImageCompressor
  scripts/ImageCompressor/imageCompressor.md
  scripts/ImageCompressor/imageCompressor.py
  scripts/ImageCompressor/requirement.txt
Labels: feature, hacktoberfest

#29 Password checker init ✨`
  scripts/Password Srength Checker/Readme.md
  scripts/Password Srength Checker/demo.png
  scripts/Password Srength Checker/main.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#35 Contributors list automated
  .github/workflows/contributors.yml
  README.md
Labels: good first issue, hacktoberfest

#36 Added text to speech scripts
  scripts/Text_To_Speech/README.md
  scripts/Text_To_Speech/requirements.txt
  scripts/Text_To_Speech/script.py
  scripts/Text_To_Speech/welcome.mp3
Labels: hacktoberfest, hacktoberfest-accepted

#38 Create voice_activated_alarm.py
  scripts/voice_activated_alaram/README.md
  scripts/voice_activated_alaram/voice_activated_alarm.py
Labels: hacktoberfest, hacktoberfest-accepted

#43 Add HTML url to PDF converter
  scripts/HTML-To-PDF/README.md
  scripts/HTML-To-PDF/requirements.txt
  scripts/HTML-To-PDF/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#48 added csv to excel converter
  scripts/CSV_to_Excel/README.md
  scripts/CSV_to_Excel/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#49 Simple script for printing Weather Reports.
  scripts/Weather_Reports/README.md
  scripts/Weather_Reports/script.py
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#26 added weather teller
  scripts/Weather-teller/README.md
  scripts/Weather-teller/weather-det.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#51 Add CSV to JSON converter
  scripts/csv_to_json/README.md
  scripts/csv_to_json/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#60 PNG to PDF converter
  scripts/PNG_To_PDF/README.md
  scripts/PNG_To_PDF/img.png
  scripts/PNG_To_PDF/png-to-pdf.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#63 Issue No: 55. tiff to png/jpeg converter
  scripts/tiff_converter/readme.md
  scripts/tiff_converter/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#75 [feat]: extract_text_from_pdf
  scripts/extract_text_from_pdf/README.md
  scripts/extract_text_from_pdf/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#74 Internet speed checker
  scripts/Internet Speed Checker/Readme.md
  scripts/Internet Speed Checker/main.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#61 Added code to create GIF from video files
  scripts/video-to-gif/requirements.md
  scripts/video-to-gif/video2gif.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#67 Issue No:57 .arff to .csv/.xlsx converter
  scripts/arff_converter/readme.md
  scripts/arff_converter/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#69 RGB to Hexadecimal converter
  scripts/RGB_To_Hexa/README.md
  scripts/RGB_To_Hexa/rgb-to-hex.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#78 translate contents of txt file from one language to another Added
  scripts/file_translater/Readme.md
  scripts/file_translater/trans.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#77 enhancement: multiple imgs to pdf
  scripts/PNG_To_PDF/README.md
  scripts/PNG_To_PDF/image1.jpg
  scripts/PNG_To_PDF/image2.jpg
  scripts/PNG_To_PDF/image3.jpeg
  scripts/PNG_To_PDF/image4.jpg
  scripts/PNG_To_PDF/image5.png
  scripts/PNG_To_PDF/image6.png
  scripts/PNG_To_PDF/img.png
  scripts/PNG_To_PDF/multipleIMGtoPDF.py
  scripts/PNG_To_PDF/png-to-pdf.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#87 Feature Request : Img to Png coverter in python
  scripts/jpg-to-png Converter/README.md
  scripts/jpg-to-png Converter/convert.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#84 QR code files ADDED
  scripts/QR_code_generator/README.md
  scripts/QR_code_generator/qr_code.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#91 Added email-validator script
  scripts/Email Validator/README.md
  scripts/Email Validator/email_validator.py
  scripts/Email Validator/requirements.txt
Labels: feature, hacktoberfest, hacktoberfest-accepted

#96 added Scheduled_shutdown script
  scripts/Scheduled_Shutdown/README.md
  scripts/Scheduled_Shutdown/shutdown.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#100 Added PDF to Voice script
  scripts/PDF to Voice/Requirements.txt
  scripts/PDF to Voice/app.py
  scripts/PDF to Voice/sample.pdf
Labels: feature, hacktoberfest, hacktoberfest-accepted

#98 Issue No: 88 pickle to txt or json
  scripts/pickle_converter/readme.md
  scripts/pickle_converter/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#105 audio extract from video two files added
  scripts/extract_audio_from_video/README.md
  scripts/extract_audio_from_video/video_to_audio.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#106 Added a instagram dp downloader script!
  scripts/Instagram DP Download/instagram_dp.py
  scripts/Instagram DP Download/requirements.txt
Labels: feature, hacktoberfest, hacktoberfest-accepted

#101 Added Check JSON format python scripts
  scripts/Check_json_format/README.md
  scripts/Check_json_format/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#112 Dishant python script
  scripts/sliceAudio_mp3/README.md
  scripts/sliceAudio_mp3/slicingAudio.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#113 Rock Paper Scissors Game
  scripts/Rock_Paper_Scissor/README.md
  scripts/Rock_Paper_Scissor/rock_paper_scissor.py
Labels: hacktoberfest-accepted

#116 Issue No: 82 RGB to Grayscale
  scripts/rgb_to_grayscale/readme.md
  scripts/rgb_to_grayscale/script.py
Labels: hacktoberfest-accepted

#119 files added for youtube video download
  scripts/Youtube_video_download/README.md
  scripts/Youtube_video_download/youtube_download.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#115 Portscanner
  scripts/Port_Scanner/readme.md
  scripts/Port_Scanner/scanner.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#120 Added crawl Google search
  scripts/Crawl Google Results/README.md
  scripts/Crawl Google Results/main.py
Labels: feature, hacktoberfest, hacktoberfest-accepted, PR:Ready-to-Review

#114 Added Snake game to play
  scripts/SnakeGame/SnakeGame.md
  scripts/SnakeGame/SnakeGame.py
Labels: PR:Ready-to-Review

#132 code to resize images
  scripts/Image_resizer/readme.md
  scripts/Image_resizer/resize.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#124 Added OpenCV Gray Image issue #117
  README.md
  scripts/OpenCV GrayImage/main.py
  scripts/OpenCV GrayImage/readme.md
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#136 RSA Encryption algo
  scripts/RSA_algo_EtoE_Encryption/README.md
  scripts/RSA_algo_EtoE_Encryption/keys/privkey.pem
  scripts/RSA_algo_EtoE_Encryption/keys/pubkey.pem
  scripts/RSA_algo_EtoE_Encryption/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#134 Add folder organizer script
  scripts/Folder-organizer/README.md
  scripts/Folder-organizer/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#137 Removed plain api keys from Weather-teller and Weather_Reports and added environment variable support in their place
  scripts/Weather-teller/.env.example
  scripts/Weather-teller/requirements.txt
  scripts/Weather-teller/weather-det.py
  scripts/Weather_Reports/.env.example
  scripts/Weather_Reports/requirements.txt
  scripts/Weather_Reports/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#138 fixed some bugs in issue #135
  scripts/Text_To_Speech/README.md
  scripts/Text_To_Speech/requirements.txt
  scripts/Text_To_Speech/script.py
  scripts/Text_To_Speech/welcome.mp3
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#141 Adding ToDo CLI program
  .gitignore
  scripts/todo_cli/README.md
  scripts/todo_cli/archive.txt
  scripts/todo_cli/done.txt
  scripts/todo_cli/todo.bat
  scripts/todo_cli/todo.py
  scripts/todo_cli/todo.txt
Labels: feature, hacktoberfest-accepted, PR:Ready-to-Review, level-2

#140 Added a new fake data generator script
  README.md
  scripts/Fake Data Generator/generator.py
  scripts/Fake Data Generator/readme.md
  scripts/Fake Data Generator/requirements.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#143 adding ImageToAscii script with editing README
  README.md
  scripts/ImageToAscii/README.md
  scripts/ImageToAscii/imgtoascii.py
  scripts/ImageToAscii/py.jpg
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#149 Adding Twitter Bot program
  scripts/twitter_streamer_bot/README.md
  scripts/twitter_streamer_bot/code.py
  scripts/twitter_streamer_bot/config.ini
  scripts/twitter_streamer_bot/requirements.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#150 added image metadata extractor script
  scripts/image_metadata_extractor/README.md
  scripts/image_metadata_extractor/requirements.txt
  scripts/image_metadata_extractor/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#151 made code quality improvements to the file_translater script
  scripts/file_translater/trans.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#158 feat: convert audio from an extension to another (e.g. mp3 to wav)
  scripts/AudioConverter/README.md
  scripts/AudioConverter/audio-converter.py
Labels: hacktoberfest-accepted

#157 PDF Page Deleting Application
  scripts/PDF-delete-pages/README.md
  scripts/PDF-delete-pages/example/Test.pdf
  scripts/PDF-delete-pages/example/Test_deleted.pdf
  scripts/PDF-delete-pages/example/screenshot1.jpg
  scripts/PDF-delete-pages/example/screenshot2.jpg
  scripts/PDF-delete-pages/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#170 Python script to split bills equally
  README.md
  scripts/bill_splitter/README.md
  scripts/bill_splitter/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#164 screen recorder
  scripts/Screen-recorder/README.md
  scripts/Screen-recorder/main.py
Labels: hacktoberfest-accepted, level-2

#162 Zodiac sign calculator
  scripts/Zodiac_Sign_Calc/README.md
  scripts/Zodiac_Sign_Calc/zodiacSignCalculator.py
Labels: hacktoberfest-accepted, level-1

#156 CMYK to RGB script added.
  scripts/CMYK To RGB/CMYKtoRGB.py
  scripts/CMYK To RGB/README.md
Labels: hacktoberfest-accepted, level-1

#123 Digital-Clock issue #128
  Digital-Clock/Digital-Clock.py
  Digital-Clock/readme.md
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#174 Added GitHub CLI project
  scripts/GithubCLI/README.md
  scripts/GithubCLI/githubCLI.py
  scripts/GithubCLI/img.png
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#178 MiniMaxAlgo added
  scripts/MiniMaxAlgo/README.md
  scripts/MiniMaxAlgo/TicTacToe.py
  scripts/MiniMaxAlgo/player.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#173 Update HACKTOBERFEST.md
  HACKTOBERFEST.md
Labels: PR:No-Issue

#181 ML based project on algo Random Forest Classifier
  Projects/DigitRecognitionusingRandomForestClassifier.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, reviewed, level-2

#192 Packet Sniffer
  scripts/packet_sniffer/README.md
  scripts/packet_sniffer/main.py
  scripts/packet_sniffer/requirements.txt
Labels: hacktoberfest-accepted, reviewed, level-2

#191 Added script for blackjack game
  scripts/Blackjack/README.md
  scripts/Blackjack/art.py
  scripts/Blackjack/main.py
Labels: hacktoberfest-accepted, reviewed, level-2

#180 Guess_the-Number in Python was added
  scripts/Guess the number/Guess_the_number.py
  scripts/Guess the number/Readme.md
Labels: hacktoberfest-accepted, reviewed, PR:Ready-to-Review, level-1

#196 Added script for PDF to PPT conversion
  scripts/PDF_to_PPT_Converter/PDF_to_PPT.py
  scripts/PDF_to_PPT_Converter/README.md
Labels: hacktoberfest-accepted, level-1

#211 Added gpa_calculator program
  scripts/gpa_calculator/README.md
  scripts/gpa_calculator/calculate.py
  scripts/gpa_calculator/screenshots/Screen Shot 2565-10-09 at 02.29.56.png
  scripts/gpa_calculator/screenshots/Screen Shot 2565-10-09 at 02.30.14.png
Labels: hacktoberfest-accepted, reviewed, level-1

#213 add sentiment analysis project
  Projects/Sentiment Analysis/Restaurant_Reviews.tsv
  Projects/Sentiment Analysis/senti.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#188 Created First Section of Game
  scripts/Text_Game/Text_Game.md
  scripts/Text_Game/Text_Game.py
Labels: hacktoberfest-accepted, reviewed, level-1

#216 202
  EMPLOYEE MANAGEMENT
  employeemanagement.py
Labels: hacktoberfest-accepted, reviewed, level-1

#219 Added YCombinator News Ranking Script - Fixed #189
  scripts/YCombinator News Ranking App/README.md
  scripts/YCombinator News Ranking App/main.py
Labels: hacktoberfest-accepted, level-1

#228 Added a Full-fledged Password Manager App using Tkinter (fixed #220)
  scripts/Password Manager App/logo.png
  scripts/Password Manager App/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#227 Chat-App
  scripts/Chat-App/Chatapp/app.py
  scripts/Chat-App/Chatapp/asgi.py
  scripts/Chat-App/Chatapp/settings.py
  scripts/Chat-App/Chatapp/urls.py
  scripts/Chat-App/README.md
  scripts/Chat-App/chat/consumers.py
  scripts/Chat-App/chat/routing.py
  scripts/Chat-App/chat/urls.py
  scripts/Chat-App/chat/views.py
  scripts/Chat-App/templates folder/LoginPage.html
  scripts/Chat-App/templates folder/chat.Page.html
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#226 Added python as well as readme file
  scripts/Detect_and_Translate_languages/README.md
  scripts/Detect_and_Translate_languages/detect_translate.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#222 Getting Wikipedia Information python script Added
  scripts/Getting_Wikipedia_Info/GetWikiInfo.py
  scripts/Getting_Wikipedia_Info/readme.md
  scripts/Getting_Wikipedia_Info/requirements.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#233 Added Pomodoro App built with Tkinter
  scripts/Pomodoro App/main.py
  scripts/Pomodoro App/tomato.png
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#238 Initial Integration of GrammarX
  scripts/grammarX/README.md
  scripts/grammarX/demoFile.txt
  scripts/grammarX/tool.py
Labels: hacktoberfest-accepted, reviewed, level-2

#232 Added files
  scripts/Image downloader/Google_image_download.py
Labels: invalid, PR:No-Issue

#240 fixed #235
  scripts/Authentication System using Flask/main.py
  scripts/Stock Alert App/main.py
Labels: hacktoberfest-accepted, reviewed, level-2

#245 Add socket programming scripts
  scripts/Socket_Programming_Python/README.md
  scripts/Socket_Programming_Python/client1.py
  scripts/Socket_Programming_Python/server1.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#243 Create pywatermark.py
  scripts/PDF Watermark/pywatermark.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#248 Added speech to text script
  scripts/Speech_To_Text/README.md
  scripts/Speech_To_Text/requirements.txt
  scripts/Speech_To_Text/sample.wav
  scripts/Speech_To_Text/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#259 Shop Inventory Manager Created
  scripts/Shop_Inventory/README.md
  scripts/Shop_Inventory/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#254 Added Wallpaper Engine
  scripts/Wallpaper Engine/requirements.txt
  scripts/Wallpaper Engine/wallhaven-dl.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#258 Added PDF Page Extractor Script
  scripts/pdf_page_extractor/README.md
  scripts/pdf_page_extractor/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#268 battery notification added
  scripts/battery_notification/README.md
  scripts/battery_notification/battery_notification.py
  scripts/battery_notification/requirement.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#272 Added Calender Project
  scripts/Calender/calender.py
  scripts/Calender/readme.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#269 Added message Encoder Decoder script
  scripts/Message Encoder and Decoder/README.md
  scripts/Message Encoder and Decoder/app.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#274 Added python-script for generate OTP
  scripts/otp_generator/generateOTP.py
  scripts/otp_generator/readme.md
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#276 Email Extractor
  scripts/Email Extractor/README.md
  scripts/Email Extractor/email_extractor.py
  scripts/Email Extractor/requirements.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#281 Added script to check typing speed
  scripts/typing-speed-checker/README.md
  scripts/typing-speed-checker/main.py
Labels: hacktoberfest-accepted, reviewed, level-1

#285 Tracking webpages [ISSUE#280]
  scripts/track_webpage_changes/README.md
  scripts/track_webpage_changes/main.py
  scripts/track_webpage_changes/requirements.txt
Labels: hacktoberfest-accepted, reviewed, level-1

#286 Added Geocoode API program
  scripts/GeoCode API/README.md
  scripts/GeoCode API/code.py
  scripts/GeoCode API/config.ini
  scripts/GeoCode API/index.html
  scripts/GeoCode API/requirements.txt
  scripts/GeoCode API/where.js
  scripts/GeoCode API/where.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#296 Add youtube_playlist_downloader script
  scripts/youtube_playlist_downloader/README.md
  scripts/youtube_playlist_downloader/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#288 Added Python Script to Encode/Decode Images
  scripts/encode-decode-images/README.md
  scripts/encode-decode-images/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#298 Added mood based movie recommendation api
  scripts/Movie_Recommendation_API/README.md
  scripts/Movie_Recommendation_API/mood_to_movie_recommender.py
  scripts/Movie_Recommendation_API/requirements.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#290 Upgrade lxml to 4.9.1 for Wallpaper Engine
  scripts/Wallpaper Engine/requirements.txt
Labels: hacktoberfest-accepted, reviewed, level-1

#299 Added BMI Calculator
  scripts/BMI/bmi.py
  scripts/BMI/readme.md
Labels: hacktoberfest-accepted, reviewed, level-1

#302 Added Video Merger
  scripts/Video_Merger/README.md
  scripts/Video_Merger/listvideos.py
  scripts/Video_Merger/main.py
  scripts/Video_Merger/renderVideo.py
  scripts/Video_Merger/requirements.txt
Labels: hacktoberfest-accepted, reviewed, PR:Ready-to-Review, level-2

#271 added alarm and number guessing game
  scripts/alarmclock/alarm.py
  scripts/alarmclock/readme.md
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#309 BASE CONVERTER CREATED
  scripts/Base_Conversion/README.md
  scripts/Base_Conversion/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#308 Added JSON to Excel converter
  scripts/json-to-excel/README.md
  scripts/json-to-excel/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#316 Feature : JSON to YAML file Converter
  README.md
  scripts/JSON-to-YAML Converter/README.md
  scripts/JSON-to-YAML Converter/json2yaml.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#318 Updates made in the README file of alarm clock software
  scripts/alarmclock/README.md
  scripts/alarmclock/readme.md
Labels: hacktoberfest-accepted, level-1

#278 Added python file for tracking product prices in Amazon
  scripts/Amazon_price_tracker/README.md
  scripts/Amazon_price_tracker/scap.py
Labels: hacktoberfest, hacktoberfest-accepted, PR:Ready-to-Review, level-2

#326 Added python script for getting day-to-day horoscope using web scraping
  scripts/Horoscope/README.md
  scripts/Horoscope/requirements.txt
  scripts/Horoscope/script.py
Labels: hacktoberfest-accepted, reviewed, level-2

#310 Added Linear Regression file to find linear relation between two rela…
  scripts/Linear Regression/Linear Regression.ipynb
  scripts/Linear Regression/README.md
  scripts/Linear Regression/example implementation/Linear Regression.ipynb
  scripts/Linear Regression/example implementation/cost_revenue_clean.csv
  scripts/Linear Regression/requirements.txt
Labels: hacktoberfest-accepted, reviewed, level-2

#328 Added Python script to download instagram videos
  scripts/instagram-downloader/README.md
  scripts/instagram-downloader/main.py
Labels: hacktoberfest-accepted, reviewed, level-2

#325 Added plagiarism checker script
  scripts/Plagiarism-checker/README.md
  scripts/Plagiarism-checker/sample1.txt
  scripts/Plagiarism-checker/sample2.txt
  scripts/Plagiarism-checker/script.py
Labels: hacktoberfest-accepted, reviewed, level-1

#330 Encoder and Decoder for .txt files
  scripts/Text_Encode_Decoder/README.md
  scripts/Text_Encode_Decoder/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#335 Web Mapping
  scripts/Web Mpping/Volcanoes.txt
  scripts/Web Mpping/Web.py
  scripts/Web Mpping/world.json
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#334 Pager duty integration
  scripts/PagerDuty-Integration/Readme.md
  scripts/PagerDuty-Integration/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#340 Added Duplicate File Remover.py script
  scripts/Duplicate File Remover/DuplicateFileRemover.py
  scripts/Duplicate File Remover/README.md
Labels: hacktoberfest-accepted, reviewed, level-2

#341 Hand Cricket Game
  scripts/Hand_Cricket_Game/README.md
  scripts/Hand_Cricket_Game/main.py
Labels: hacktoberfest-accepted, reviewed, level-1

#344 Chore: Added QR
  scripts/QR_gen_sage/README.md
  scripts/QR_gen_sage/qr.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#342 added attendance automation script
  scripts/attendance_automation/attendance-automation.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#313 Added Program for weather notifications in desktop
  scripts/Weather_Notifications_Desktop/weather_Notifications_Desktop.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#353 Added Sudoku Solver
  scripts/Sudoku-Solver/README.md
  scripts/Sudoku-Solver/main.py
Labels: hacktoberfest-accepted, level-1

#360 Add Confusion Matrix
  scripts/Confusion_Matrix/README.md
  scripts/Confusion_Matrix/make_confusion_matrix.py
Labels: feature, hacktoberfest-accepted, PR:Ready-to-Review

#355 #338 Created GUI_Dictionary
  scripts/GUI_Dictionary/GUI_Dictionary.py
  scripts/GUI_Dictionary/README.md
  scripts/GUI_Dictionary/screenshots/gui-dict-3.png
  scripts/GUI_Dictionary/screenshots/gui-dict-4.png
  scripts/GUI_Dictionary/screenshots/gui_dict1.png
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#365 Automate OS by using python
  scripts/Automate OS/Automate_OS.py
  scripts/Automate OS/Readme.md
  scripts/Whatsapp Automation/Readme.md
  scripts/Whatsapp Automation/Whatsapp.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#362 Added Whatsapp Automation file into scripts folder
  scripts/Whatsapp Automation/Readme.md
  scripts/Whatsapp Automation/Whatsapp.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#337 Created the GUI Internet Speed Tester
  scripts/Internet Speed Tester/Readme.md
  scripts/Internet Speed Tester/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#376 Added Tetris Game
  scripts/Tetris-Game/README.md
  scripts/Tetris-Game/main.py
  scripts/Tetris-Game/requirements.txt
Labels: hacktoberfest-accepted, reviewed, level-2

#349 Script to fetch all the wifi passwords
  scripts/fetching_system_information/README.md
  scripts/fetching_system_information/script.py
  scripts/wifi_password_checker/README.md
  scripts/wifi_password_checker/script.py
Labels: hacktoberfest-accepted, level-2

#388 created level 2
  scripts/Text_Game/Text_Game.py
Labels: hacktoberfest-accepted, level-1

#387 Script for fetching Youtube channel info
  scripts/fetching_system_information/README.md
  scripts/youtube_channel_info/README.md
  scripts/youtube_channel_info/script.py
Labels: hacktoberfest-accepted, level-1

#393 Music Player GUI
  scripts/Music Player/README.md
  scripts/Music Player/music-player.py
  scripts/Music Player/requirements.txt
Labels: hacktoberfest-accepted, level-2

#399 Script to fetch quotes
  scripts/Quotes Fetch/readme.md
  scripts/Quotes Fetch/scrape.py
Labels: hacktoberfest-accepted, level-1

#401 Added extract_text_from_image script
  scripts/Extract_TEXT_FROM_IMAGE/README.md
  scripts/Extract_TEXT_FROM_IMAGE/main.py
  scripts/Extract_TEXT_FROM_IMAGE/requirements.txt
  scripts/Extract_TEXT_FROM_IMAGE/test1.png
Labels: hacktoberfest-accepted, level-1

#418 Added age calculator script- issue solved #417
  README.md
  scripts/Calculate_your_age_script/script.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#408 Created Level 3 and refactored code
  scripts/Text_Game/Text_Game.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-1

#428 Add lyrics scraper script
  scripts/Lyrics Scraper/LyricsScraper.py
  scripts/Lyrics Scraper/README.md
  scripts/Lyrics Scraper/requirements.txt
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#433 Adding script for Checksum
  scripts/checksum/README.md
  scripts/checksum/checksum.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-3

#431 Added Brick Breaker
  scripts/Brick-Breaker-Python/README.md
  scripts/Brick-Breaker-Python/main.py
Labels: hacktoberfest-accepted, PR:Ready-to-Review, level-2

#434 Delete scripts/typing-speed-checker directory
  scripts/typing-speed-checker/README.md
  scripts/typing-speed-checker/main.py
Labels: bug, feature, hacktoberfest, hacktoberfest-accepted

#435 Delete scripts/csv_to_json directory
  scripts/csv_to_json/README.md
  scripts/csv_to_json/script.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#436 Delete scripts/Base_Conversion directory
  scripts/Base_Conversion/README.md
  scripts/Base_Conversion/main.py
Labels: feature, hacktoberfest, hacktoberfest-accepted

#461 Dice Roll
  scripts/Dice Roll/main.py
  scripts/Dice Roll/readme.md
  scripts/Tic-Tac-Toe/main.py
  scripts/Tic-Tac-Toe/readme.md
Labels: hacktoberfest-accepted, PR:Ready-to-Review
